grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.ology.vn
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.ology.vn
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.ology.vn/auth
      token_url: https://dex.ology.vn/token
      api_url: https://dex.ology.vn/userinfo
  alerting:
    contactpoints.yaml:
      secret:
        contactPoints:
          - name: ntfy
            receivers:
              - uid: ntfy-relay
                type: webhook
                settings:
                  url: http://ntfy-relay.ntfy-relay
                  username: admin
                  password: $__env{NTFY_RELAY_PASSWORD}
    policies.yaml:
      policies:
        - receiver: ntfy
          group_by:
            - grafana_folder
            - alertname

  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # selectorLabels: {}
    ## Sub-directory of the PV to mount. Can be templated.
    # subPath: ""
    ## Name of an existing PVC. Can be templated.
    # existingClaim:
    ## Extra labels to apply to a PVC.
    extraPvcLabels: {}

    ## If persistence is not enabled, this allows to mount the
    ## local storage in-memory to improve performance
    ##
    inMemory:
      enabled: false
      ## The maximum usage on memory medium EmptyDir would be
      ## the minimum value between the SizeLimit specified
      ## here and the sum of memory limits of all containers in a pod
      ##
      # sizeLimit: 300Mi